### ISSUE TITLE
Errors in 3.2

### ISSUE THREAD

**Issue by jwensley2** [capistrano/capistrano#1022]
I'm getting these errors in 3.2 for a config that worked in 3.1.

```
** Invoke deploy:check:linked_dirs (first_time)
** Execute deploy:check:linked_dirs
** Invoke deploy:check:make_linked_dirs (first_time)
** Execute deploy:check:make_linked_dirs
** Invoke deploy:check:linked_files (first_time)
** Execute deploy:check:linked_files
** Invoke deploy:set_previous_revision (first_time)
** Execute deploy:set_previous_revision
cap aborted!
NoMethodError: undefined method `join' for nil:NilClass
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/capistrano-3.2.0/lib/capistrano/tasks/deploy.rake:215:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:54:in `run'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/sshkit-1.4.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:set_previous_revision
The deploy has failed with an error: #<NoMethodError: undefined method `join' for nil:NilClass>
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```
