### ISSUE TITLE
Capistrano 2.14.2 in ruby 2.0.0 throws error `alias_method': undefined method `invoke_task_directly'

### ISSUE THREAD

**Issue by rutikasb** [capistrano/capistrano#579]
In our deploy script, we're using  invoke_task_directly_without_callbacks find_task(<task_name>)
 When we upgraded ruby to 2.0.0-p247, it started throwing the following error.

/home/rutika/.rvm/gems/ruby-2.0.0-p247@spaghetti/gems/capistrano-2.14.2/lib/capistrano/configuration/namespaces.rb:10:in `alias_method': undefined method`invoke_task_directly' for class `Capistrano::Configuration::Namespaces::Namespace' (NameError)

We are on rails version 3.2.13 and ubuntu 12.04 LTS. It was working fine on ruby-1.9.3-p194 for the same version of capistrano.
